#!/bin/bash

# the tool location
esptool=~/.local/lib/python2.7/site-packages/esptool.py

# run the tool with options matching NodeMCU Dev Kit 1.0
# all script arguments are passed to the tool
python $esptool  -p /dev/ttyUSB0 write_flash -fm dio -fs 32m 0x00000 $@